/**export interface Pageable {
  data_elements: any[];
  total_elements: number;
}**/

import { Empresa } from 'src/app/menu/pages/empresas/core/models/main.model';

// Generated by https://quicktype.io

export interface Pageable<T> {
  content: T[];
  pageable: Page;
  last: boolean;
  totalPages: number;
  totalElements: number;
  size: number;
  number: number;
  sort: Sort;
  first: boolean;
  numberOfElements: number;
  empty: boolean;
}

export interface Page {
  sort: Sort;
  offset: number;
  pageSize: number;
  pageNumber: number;
  paged: boolean;
  unpaged: boolean;
}

export interface Sort {
  empty: boolean;
  sorted: boolean;
  unsorted: boolean;
}
